### ISSUE TITLE
Cannot scroll Filter/Split thingies

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#10]
When I have enough things in the filter or split, it fills the entry thingie bobber and I cannot scroll to `X` out the values.  That's unfortunate.

**Comment by vogievetsky** [comment]
This needs improvement. Temporary solution: get a wider monitor :-p

**Comment by vogievetsky** [comment]
Boom. after being in 'coming soon' status for over a month it is here.

Feast your eyes on the "overflow"

![image](https://cloud.githubusercontent.com/assets/177816/11599474/f6afd680-9a7b-11e5-9e4c-7af928ee1619.png)
