### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by code-artisan** [implydata/pivot#106]
Hi there,  can you create a new file to note the change logs?

**Comment by vogievetsky** [comment]
There is a section in the readme: https://github.com/implydata/pivot#roadmap for recent improvements. Are you thinking something more in depth than that?

**Comment by vogievetsky** [comment]
Hi as of version 0.8 pivot will have an official change log: https://github.com/implydata/pivot/blob/master/CHANGELOG.md

**Comment by code-artisan** [comment]
:+1: :100:
