### ISSUE TITLE
exception in timeseries query with multiple hyperunique measures

### ISSUE THREAD

**Issue by sascha-coenen** [implydata/pivot#107]
We have several measures defined in Pivot which are expressions over hyperuniques. 
Some expressions have the same hyperunique count in the denominator:

avgWinPrice:  $main.sum($winPrice) / $main.countDistinct($sessionId)
fillrate: $main.sum($served) / $main.countDistinct($sessionId)

When selecting the above two measures, Pivot produces the druid query contained below and throws the exception below. It seems that the exception is due to the fact that the aggregations section in the query contains the same hyperUnique field twice with the same name and the same field name.
This only seems to happen in the case of hyperUnique counts as far as I can tell.

EXCEPTION:
`Got error in query 80: Instantiation of [simple type, class io.druid.query.timeseries.TimeseriesQuery] value failed: [%s] already defined (in 234ms)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  error: Instantiation of [simple type, class io.druid.query.timeseries.TimeseriesQuery] value failed: [%s] already defined
  Error: Instantiation of [simple type, class io.druid.query.timeseries.TimeseriesQuery] value failed: [%s] already defined
      at /opt/plywood/node_modules/imply-pivot/node_modules/plywood-druid-requester/build/druidRequester.js:132:93
      at _fulfilled (/opt/plywood/node_modules/imply-pivot/node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (/opt/plywood/node_modules/imply-pivot/node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (/opt/plywood/node_modules/imply-pivot/node_modules/q/q.js:796:13)
      at /opt/plywood/node_modules/imply-pivot/node_modules/q/q.js:604:44
      at runSingle (/opt/plywood/node_modules/imply-pivot/node_modules/q/q.js:137:13)
      at flush (/opt/plywood/node_modules/imply-pivot/node_modules/q/q.js:125:13)
      at process._tickCallback (node.js:415:13)
  POST /plywood?by= 500 239.330 ms - 156`

------------------
QUERY:
`  {
    "queryType": "timeseries",
    "dataSource": "MappingTest",
    "intervals": [
      "2016-02-14T14/2016-02-15T14"
    ],
    "granularity": "all",
    "context": {
      "timeout": 30000
    },
    "aggregations": [
      {
        "name": "_sd_0",
        "type": "doubleSum",
        "fieldName": "served"
      },
      {
        "name": "_sd_1",
        "type": "hyperUnique",
        "fieldName": "sessionId"
      },
      {
        "name": "_sd_2",
        "type": "doubleSum",
        "fieldName": "winPrice"
      }
    ],
    "postAggregations": [
      {
        "type": "hyperUniqueCardinality",
        "fieldName": "_sd_1",
        "name": "_sd_1_fin"
      },
      {
        "type": "hyperUniqueCardinality",
        "fieldName": "_sd_1",
        "name": "_sd_1_fin"
      },
      {
        "type": "arithmetic",
        "fn": "/",
        "fields": [
          {
            "type": "fieldAccess",
            "fieldName": "_sd_0"
          },
          {
            "type": "fieldAccess",
            "fieldName": "_sd_1_fin"
          }
        ],
        "name": "fillrate"
      },
      {
        "type": "arithmetic",
        "fn": "/",
        "fields": [
          {
            "type": "fieldAccess",
            "fieldName": "_sd_2"
          },
          {
            "type": "fieldAccess",
            "fieldName": "_sd_1_fin"
          }
        ],
        "name": "avgWinPrice"
      }
    ]
  }`

**Comment by vogievetsky** [comment]
I just updated Pivot with the latest Plywood. This should no longer happen.
I am going to close this issue. Please reopen if there is still a problem with Pivot >= 0.7.34

**Comment by sascha-coenen** [comment]
awesome! thank you so much. I tested it and it works fine!
