### ISSUE TITLE
Having trouble with using `plywood-mysql-requester`

### ISSUE THREAD

**Issue by kyuseobkim** [implydata/pivot#108]
I'm getting the following error while running `gulp`

```
error TS2307 Cannot find module 'plywood-mysql-requester'
```

**Comment by vogievetsky** [comment]
Thank you for reporting this. It was my typo:

This was the problem: https://github.com/implydata/plywood-mysql-requester/commit/cc9915910ae98b4830ebd91bc71bf4d6cf7f6764

plywood-mysql-requester should work as of version 1.2.2

I upgraded the version imported by Pivot and made sure it works by importing it: https://github.com/implydata/pivot/commit/3d15294ba832e72e219e0ed1b38f24f18017edfc
