### ISSUE TITLE
Resize the pin Board

### ISSUE THREAD

**Issue by b-slim** [implydata/pivot#109]
Hi All,
I am not sure if there is a way to resize the pin board, in fact the way it is now i can read long dimension names, due to the limited size. As you can see for metrics i can not see what is there.

**Comment by b-slim** [comment]
![screen shot 2016-02-25 at 7 57 18 am](https://cloud.githubusercontent.com/assets/7376396/13321583/7e83cb34-db95-11e5-9017-a7f8b555e33f.png)

**Comment by vogievetsky** [comment]
Hi that feature is on the roadmap.

**Comment by b-slim** [comment]
@vogievetsky any ETAs ?

**Comment by vogievetsky** [comment]
This is implemented in 0.8.29

**Comment by vogievetsky** [comment]
![image](https://cloud.githubusercontent.com/assets/177816/15258310/b2c85ed0-18ff-11e6-8a7e-524374fdb82a.png)

🎆
