### ISSUE TITLE
Change the metric that dimensions are sorted by

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#11]
When I look at dimensions in the "pinned" area or after clicking on a dimension in the left pane, I cannot seem to change which metric it is sorting by.  I'd really like to be able to do that.

**Comment by fjy** [comment]
+1

**Comment by asherbitter** [comment]
+1, this is really important and should be coming relatively soon.

**Comment by vogievetsky** [comment]
This is fixed in the latest release :-)
