### ISSUE TITLE
Relative Time

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#112]
The new relative time changes are nice and make it easier to build URLs that can just be used as jumping points to see what's going on right now.

It does, however, make it difficult to do some things:

1. I used to be able to just click Split-Time -> "1H" and it would update my timeline, now it doesn't do anything.  A simple way to say "snap to recent" or something without refreshing the entire page would be nice.
2. If I'm looking at something "relative" and I want to share it, the URL will be relative.  Can you make a simple "share-exactly-my-screen" button that will put a non-relative URL into my clipboard for sharing?

**Comment by vogievetsky** [comment]
1. Working on this
2. Interesting

**Comment by vogievetsky** [comment]
Both of these have been addressed in this PR: https://github.com/implydata/pivot/pull/132
Available in latest Pivot (0.7.48)
Check out the new refresh and the share buttons in the header.
