### ISSUE TITLE
Show timezone in UI

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#113]
When I'm hovering over time points, it appears to show me UTC time.  The x-axis is however local time.  I often forget which is which.  It would be great if the tooltip could include "UTC" just to remind me that it is showing me UTC time.

**Comment by cybermarkus1** [comment]
+1. Why not use same local time on both?

**Comment by ddlatham** [comment]
Also the Timezone for the Filter appears to be UTC which is confusing in that it doesn't match the x axis

**Comment by vogievetsky** [comment]
The x-axis labeling was a bug that was was fixed in yesterdays 0.8 release

**Comment by vogievetsky** [comment]
Latest Pivot release (0.8.22) comes with a timezone selection UI and comprehensive timezone support.
