### ISSUE TITLE
Pinboard metric selector dropdown doesn't scroll

### ISSUE THREAD

**Issue by kzadorozhny** [implydata/pivot#114]
On the pinboard it's impossible to select a metric that doesn't fit the screen. For the data sources with high number of metrics it's quite limiting.

Pivot version: 0.7.24

<img width="1401" alt="pivot_screenshot" src="https://cloud.githubusercontent.com/assets/1616702/13470587/c44edfa2-e061-11e5-9ff8-3a352296da39.png">

**Comment by vogievetsky** [comment]
Holly molly that is a lot of Measures. Will fix that.

**Comment by vogievetsky** [comment]
Fixed in 0.7.36
