### ISSUE TITLE
Split on long dimensions

### ISSUE THREAD

**Issue by maximenay** [implydata/pivot#115]
Hi,

When splitting on long dimensions, we're unable to actually see the value of the dimension. That would be great if we could see it, and somehow copy/paste it.

![screenshot from 2016-03-02 19 03 15](https://cloud.githubusercontent.com/assets/4480772/13483494/9c81c1c2-e0a9-11e5-83e7-c5d9b4ca62af.png)

**Comment by asherbitter** [comment]
Though there is no good way to see it at the moment. Would be great indeed.

It is, however, possible to copy a value by clicking on a row and choosing "copy value".

<img width="941" alt="screen shot 2016-04-24 at 9 34 53 pm" src="https://cloud.githubusercontent.com/assets/957611/14769609/b699efd2-0a64-11e6-90fc-c0d92bdab8ea.png">

**Comment by maximenay** [comment]
Yes, the copy/paste functionality has been introduced after I opened this issue.
Visualizing it would make things a bit easier, but being able to copy/paste it is already very helpful!
