### ISSUE TITLE
Filter Search functionality broken for dimensions with Lookups

### ISSUE THREAD

**Issue by peter-triplelift** [implydata/pivot#119]
When searching, the list disappears after a brief moment. Video: http://screenshot.3lift.com/0s2p0G1U1n2n

**Comment by vogievetsky** [comment]
What version of Pivot are you using? (What does it say on the browser tab?)

**Comment by peter-triplelift** [comment]
0.7.28

**Comment by peter-triplelift** [comment]
1. Yes, it happens on Pivot 0.7.35 as well.
2. It's reproducible on other dimensions (typically large dimensions).
3. The publisher dimension is around 3500 values.

It seems to only be happening on dimensions with lookups. I have Tactic_Id as well as Tactic_Name as possible dimensions, and Tactic_Id is correctly searching, while Tactic_Name is not. There's also another dimension with a lookup that has < 100 distinct values, and that is also searching correctly

Thanks!

**Comment by peter-triplelift** [comment]
Quick update: I changed the date range so that dimension with <100 values had >100 values. The search functionality no longer worked. Hope this helps, and thanks for the quick responses!

**Comment by vogievetsky** [comment]
Lookups you say... ok I have not tested it yet but I bet that is where the problem lies.

**Comment by vogievetsky** [comment]
Yep it's the lookups that spoil it, can confirm.
Plywood can not evaluate `$tactic_Id.lookup(your_lookup_name).contains('wiki')` in Druid.

Good news: there is a new Druid feature that will allow this to work that [I have asked for presciently](https://github.com/druid-io/druid/issues/1875).
Bad news: this [fix](https://github.com/druid-io/druid/pull/2209) is part of the Druid 0.9.0 milestone

I will make this work with Plywood (ETA: 1 week) but it will only work for people who are running Druid 0.9.0 or better. So you will probably need to upgrade your Druid as well as your Pivot for this to work.

People using lookup with Druid <= 0.8.3 will have to live with broken search forever. I will add an error message to that menu though.

**Comment by vogievetsky** [comment]
Just to be clear: at the time of this comment Druid 0.9.0 has not been released yet.

**Comment by peter-triplelift** [comment]
Thanks for the info, Vadim! Do you know an approximate timeline for when Druid 0.9.0 will be released?

**Comment by vogievetsky** [comment]
According to @gianm, who is sitting next to me: "There is no official timeline, but ether end of next week or the week after. Probably the week after"

**Comment by peter-triplelift** [comment]
That works, thanks!

**Comment by vogievetsky** [comment]
I would rather keep the issue opened until the Pivot side of the fix is shipped.

**Comment by vogievetsky** [comment]
Alright so latest pivot (0.7.41) will present you with a nice error message feedback now. Once you upgrade to druid 0.9.0 it will magically start working (and be faster in many ways as well). I tried it with 0.9.0_rc3: works like a charm.

**Comment by peter-triplelift** [comment]
Awesome, Vadim. Thanks so much!

**Comment by vogievetsky** [comment]
Wooooo Druid 0.9.0 is out finally. (for anyone following this thread) If you are using Pivot I strongly advice  upgrading to 0.9.0 there are a TON of improvements in the Pivot <-> Druid communication.

**Comment by peter-triplelift** [comment]
Awesome, thanks for the update! The search functionality works perfectly now.
