### ISSUE TITLE
Hard to read time x axis

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#12]
<img width="772" alt="screen shot 2015-09-17 at 2 59 41 pm" src="https://cloud.githubusercontent.com/assets/216778/9944582/d6c5fa7c-5d4d-11e5-83b8-52a49f293a2d.png">

I find this x-axis really hard to read.  If we are spanning multiple days, can the x-axis just be the day and we get more fine-grained data from the tooltip?

**Comment by fjy** [comment]
I agree

**Comment by asherbitter** [comment]
Agree and it's on the roadmap. Both axes have not yet been adjusted.

**Comment by vogievetsky** [comment]
This had been improved in the latest release 0.8.22 but there is still some way to go.
