### ISSUE TITLE
Time Filter overflow

### ISSUE THREAD

**Issue by ayxos** [implydata/pivot#121]
When i set a time filter, e.g. between 3:23 and 9:23 and split by time(hour) i have an overflow:

<img width="1434" alt="screen shot 2016-03-10 at 10 37 42" src="https://cloud.githubusercontent.com/assets/3403938/13665464/ecdc3658-e6ac-11e5-87ac-ca70034fff98.png">

The backend returns the following result:

```
TIME: {start: "2016-03-10T09:00:00.000Z", end: "2016-03-10T10:00:00.000Z", type: "TIME_RANGE"}
end: "2016-03-10T10:00:00.000Z"
start:"2016-03-10T09:00:00.000Z"
type:"TIME_RANGE"
added: 1133428
count: 3924
deleted:-81425
```

So, between 9:00 (10:00 CET) and 10:00 (11:00 CET) there is only one result that should appear in the middle, 09:30 (10:30 CET). But the Y Axis has been set at the end of the timeframe requested, 09:23 , results in overflow.

<img width="140" alt="screen shot 2016-03-10 at 10 51 03" src="https://cloud.githubusercontent.com/assets/3403938/13665697/04477de2-e6ae-11e5-82d2-f4a9ad8a03f3.png">

**Comment by alodium** [comment]
Hi guys.
Any news about this bug?

**Comment by alodium** [comment]
Ok, after some debugging we found the issue:
Apparently, in /filter-clause/filter-clause.ts line 64, there is an adding of one minute to each start range of max time.

Looks like this line was written under the testing of minutes granularity, where it makes sense.
In the case of hours, it is just shifting the whole graph to the right.

This can be solved also by "cutting" the graph from the right (maxtime - 6) -1 but this will not give the requested results.

Question is: is there a real importance with this line? is it solving more than it is breaking, in this case?

Thanks!
