### ISSUE TITLE
window.autoRefresh never called

### ISSUE THREAD

**Issue by x4base** [implydata/pivot#122]
In pivot/src/client/components/cube-view/cube-view.tsx:126, 
we can see 
`    (window as any).autoRefresh = () => {`,
but I can't find any usage of this function.
I find this function very helpful. Is this function currently for debugging only? Or is it actually called somewhere?

**Comment by vogievetsky** [comment]
The auto refresh has been shipped in the latest Pivot ( https://github.com/implydata/pivot/pull/132 )
