### ISSUE TITLE
Ability to set default filters via query parameters

### ISSUE THREAD

**Issue by emtiazahmed** [implydata/pivot#123]
It would be awesome to have default filters based on query parameters in url. We have a usecase, where  we save pivot reports via hashes in the url. It would be nice to pass default filters via url as well so that user can start with something we prefer them to start with.

Example:

http://pivot-host:port/pivot/.....?filters={...}

What do you guys think?

**Comment by vogievetsky** [comment]
This is in the works

**Comment by dangoldin** [comment]
I've been trying to do this by reverse engineering the hash but haven't made a ton of progress. It looks as if it's base64 encoded along with some LZMA compression. Is there a quick way to go to/from the hash to the options?

**Comment by evasomething** [comment]
Hi, with the new pivot release you can generate a hash by posting some configurations to /mkurl route
We'll be supporting this way of hash generation in the future. 

Full docs are here: 
https://github.com/implydata/pivot/blob/master/docs/generating-links-into-pivot.md
