### ISSUE TITLE
kind: number doesn't work

### ISSUE THREAD

**Issue by alodium** [implydata/pivot#134]
Until this version, kind: number was not supported.

I saw that from ver 49 it is, but it looks like the frontend is not ready for it.

When selecting a measure with a kind: number as a filter, and trying to select the checkboxes, I get the error:

`Uncaught Error: unknown kind number`

In the code, it is looks like number is not valid:

`switch (dimension.kind) {

	        case 'string':

	        case 'boolean':

	            var setElements = clause.getLiteralSet().elements;

	            label += setElements.length > 1 ? " (" + setElements.length + ")" : ": " + setElements[0];

	            break;
	        case 'time':

	            var timeSelection = clause.selection;

	            var timeRange = essence.evaluateSelection(timeSelection);

	            label = date_1.formatTimeRange(timeRange, essence.timezone, date_1.DisplayYear.IF_DIFF);

	            break;

	        default:

	            throw new Error('unknown kind ' + dimension.kind);

	    }`

Was it forgotten there or that I am implementing the config file in a wrong way?

Thanks.

PS: when adding `case 'number':` to the code, everything works.

**Comment by vogievetsky** [comment]
ops.. it it should be there.

**Comment by alodium** [comment]
Thanks!

**Comment by vogievetsky** [comment]
Thank you for filing the issue :-)
Should be fixed in 0.7.51
