### ISSUE TITLE
Cannot print config

### ISSUE THREAD

**Issue by iyurinok** [implydata/pivot#137]
I am using the latest (0.7.49) version of pivot and trying to print its config:
```
: ~$ pivot -druid druidquery-1-001:8082 --print-config
There was an error generating a config: Could not find any data sources please verify network connectivity
```

This error looks weird as I can connect to this host:
```
: ~$ pivot -druid druidquery-1-001:8082
Starting Pivot v0.7.49
Will refresh data source list every 10000ms
Listening on 9090
Adding Druid data source: 'live_bi_event'
Adding Druid data source: 'batch_bi_event'
Initial load and introspection complete. Got 2 data sources, 2 queryable
```

If I downgrade pivot to old version (0.7.27) everything works fine.

**Comment by jonathanhle** [comment]
+1 we had the same issue.

**Comment by vogievetsky** [comment]
I also discovered that and fixed it last night. Could you please try again with latest 0.7.51 and reopen this issue if it does not work.
