### ISSUE TITLE
 Data import functionality on pivot

### ISSUE THREAD

**Issue by narsi345** [implydata/pivot#144]
can we have options on the UI to download data in csv  ?

**Comment by kastsiushkin** [comment]
There is an open issue [#57](https://github.com/implydata/pivot/issues/57)

**Comment by vogievetsky** [comment]
Export to CSV was added in Pivot 0.8.15.

**Comment by narsi345** [comment]
Thanks very much

On Thu, Apr 21, 2016 at 2:23 PM, Vadim Ogievetsky <notifications@github.com>
wrote:

> Export to CSV was added in Pivot 0.8.15.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/implydata/pivot/issues/144#issuecomment-213119210>
>



-- 
narsi
