### ISSUE TITLE
Bad status code

### ISSUE THREAD

**Issue by code-artisan** [implydata/pivot#151]
Failed to introspect data source: 'xxx' because Bad status code
Failed to introspect data source: 'xxx' because Bad status code
Initial introspection complete. Got 2 data sources, 0 queryable

Can not get queryable datasources. why?

**Comment by vogievetsky** [comment]
What is the status code reported?
Can you run with --verbose mode and attach offending query?

**Comment by code-artisan** [comment]
@vogievetsky 

vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 1:
{
  "queryType": "segmentMetadata",
  "dataSource": "xxx",
  "merge": true,
  "analysisTypes": [
    "aggregators"
  ],
  "lenientAggregatorMerge": true
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
Will refresh data sources every 10000ms
Listening on 9090
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got error in query 1: Bad status code (in 110ms)
^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to introspect data source: 'xxx' because Bad status code
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 2:
{
  "queryType": "sourceList"
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got result from query 2: (in 39ms)
[
  "xxx",
  "xxx"
]
^^^^^^^^^^^^^^^^^^^^^^^^^^
Adding Druid data source: 'xxx'
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 3:
{
  "queryType": "segmentMetadata",
  "dataSource": "xxx",
  "merge": true,
  "analysisTypes": [
    "aggregators"
  ],
  "lenientAggregatorMerge": true
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 4:
{
  "queryType": "segmentMetadata",
  "dataSource": "xxx",
  "merge": true,
  "analysisTypes": [
    "aggregators"
  ],
  "lenientAggregatorMerge": true
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got error in query 4: Bad status code (in 42ms)
^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to introspect data source: 'xxx' because Bad status code
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got error in query 3: Bad status code (in 44ms)
^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to introspect data source: 'xxx' because Bad status code
Initial introspection complete. Got 2 data sources, 0 queryable
