### ISSUE TITLE
There are no datasources configured

### ISSUE THREAD

**Issue by l15k4** [implydata/pivot#155]
Hey,

I just tried quickstart in distribution 1.2.0 (with druid 0.9.0) using `distribution-docker`, I indexed stuff in there so that : 
```
$ curl -XGET http://localhost:8081/druid/coordinator/v1/datasources
["foo"]

$ curl -XGET http://localhost:8081/druid/coordinator/v1/datasources/foo
{"tiers":{"_default_tier":{"size":155675892,"segmentCount":166}},"segments":{"maxTime":"2016-02-22T00:00:00.000Z","size":155675892,"minTime":"2015-01-01T00:00:00.000Z","count":166}}
```

But if I go to `localhost:9095/pivot` it says : "There are no datasources configured" ... Even `localhost:9095/pivot#foo` does so.

Any idea what might be wrong ? It was working for me until I tried distribution 1.2.0

**Comment by l15k4** [comment]
I see, there is this log message : 
```
Failed to load data source: 'foo' because 'c-geo:c3' is not a URL safe name. Try 'c-geo_c3' instead?
```
Any idea how to deal with this? I cannot change it in the source json files.

**Comment by l15k4** [comment]
I asked the question on [google groups](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/imply-user-group/od4HNulzwpg)

**Comment by vogievetsky** [comment]
Hi as off Pivot 0.8.15 url safe names will be automatically created when introspecting a data source with non url safe dimension names. Thinks should 'just work now'.
