### ISSUE TITLE
Error while filtering on time in time-split table view

### ISSUE THREAD

**Issue by gianm** [implydata/pivot#16]
Steps to reproduce:

1. Open up a table with a time split.
2. Click on a row, then click on the checkmark √.
3. Get the errors: "Uncaught TypeError: Cannot read property 'getTime' of undefined" and "Uncaught TypeError: Cannot read property 'valueOf' of undefined"

**Comment by vogievetsky** [comment]
https://github.com/implydata/pivot/commit/62d1688bb10e87a691fa9d176dfa4dbaf44e4f54
