### ISSUE TITLE
Bringing  back custom Time  ranges in the Time Filter 

### ISSUE THREAD

**Issue by narsi345** [implydata/pivot#181]
The minute::second specific option while selecting Time Filter is missing from 0.8.22 and later versions.Can we bring back  ?

![time_range_selection_missing](https://cloud.githubusercontent.com/assets/3916780/15132250/72c42c4c-160c-11e6-94e4-5afa42c4a93d.png)

thanks
narasimhan

**Comment by vogievetsky** [comment]
Hi, the new Pivot features a date picker for more easily selecting days and a timezone selector. The idea of the time selection was to make up for the fact that everything used to be UTC before so you needed to enter a time if you wanted to see a full day of data. What is your use case for needing to change the time?

**Comment by narsi345** [comment]
Thanks for asking.our infra is running parallel pipeline example batch and
realtime on grid (as hive tables) and in addition our druid pipeline for
realtime.

So when we do DQ check between pipelines especially between  realtime on
grid and our druid pipeline we wanted to check between
time1:10:10-time2:20:35. This is one of a specific request from one the
customer  but if it will not add value or not the right way , then its fine
not to proceed with that.

thanks
narasimhan

On Tue, May 10, 2016 at 9:34 AM, Vadim Ogievetsky <notifications@github.com>
wrote:

> Hi, the new Pivot features a date picker for more easily selecting days
> and a timezone selector. The idea of the time selection was to make up for
> the fact that everything used to be UTC before so you needed to enter a
> time if you wanted to see a full day of data. What is your use case for
> needing to change the time?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/implydata/pivot/issues/181#issuecomment-218215137>
>



-- 
narsi

**Comment by scboffspring** [comment]
Agree.

Sometimes I want to see data, for debugging purpose, from 12:15 to 12:35 because we may have trouble etc.

Please bring back the time selector.

**Comment by wangpeibin713** [comment]
Agree
We need the time selector too ,please bring it back

**Comment by hollow** [comment]
We're also missing the time picker, would be awesome to have it back

**Comment by vogievetsky** [comment]
We are going to bring it back and then some. Filter selection is going to be 🍌 s
