### ISSUE TITLE
Showing all visualization in a single page for a single query.

### ISSUE THREAD

**Issue by narsi345** [implydata/pivot#182]
Can we have a tiled /stacked view of all visualization available in pivot on a single page. ? 

Example like  
             count, Tables , time series graphs , bar chart visualization for a single query showing as stacked  together. (Something like caravel displays)

This came as a requirement from our editorial customers.

<img width="719" alt="all_in_one_view" src="https://cloud.githubusercontent.com/assets/3916780/15132336/5aaafa7c-160d-11e6-81d9-888b769401a7.png">

thanks 
narasimhan

**Comment by asherbitter** [comment]
A tiled view is on the roadmap, although there is no timeline at the moment.
