### ISSUE TITLE
Exporting to CSV does not export all columns

### ISSUE THREAD

**Issue by mattallty** [implydata/pivot#183]
Hi,

I've been using the new "export to csv" feature and I've reached a pretty annoying problem:

Let's say I've the following dataset:

- dimensions:
 - region
 - city

- measures:
 - population
 - buildings

If I'm visualizing my dataset using 2 splits, "region" and "city", I can see 2 levels in the first column. (region -> city, with corresponding measures), but when exporting data to CSV, I've only one split, the last one (here, "city").

Is this the expected behaviour ?
How could I export exactly the structure I see in the pivot UI ?

thanks again for your great work !

**Comment by vogievetsky** [comment]
Hi, this is an artifact of how the data is loaded at the moment it will be fixed soon.

**Comment by vogievetsky** [comment]
Hi this should be fixed now. Working on making the download column ordering more user friendly now.

**Comment by peter-triplelift** [comment]
@vogievetsky Hi, I seem to still be experiencing this problem. I'm on Pivot version 0.9.39. Was this issue reintroduced on accident since May 19th?

I have two splits in Pivot in the table view, but when I export I only get the second split dimension.

Thanks!
