### ISSUE TITLE
Authentication in Pivot

### ISSUE THREAD

**Issue by bikash1605** [implydata/pivot#185]
How can i establish token based authentication in pivot ?

**Comment by arunkjn** [comment]
I saw that there is a provision of auth parameter in config and it will require a corresponding auth module, How can we integrate a auth module like passport with pivot? Any examples will be appreciated.

**Comment by vogievetsky** [comment]
You can use the auth hook to integrate an authentication module, we are actually revisiting it right now to be more useful.

**Comment by priteshdamani** [comment]
@vogievetsky great job on the project so far. We are thinking about adopting this, however, this ticket is a crucial point for us. Do you have any pointers on how to go about implementing it. May be we can do a PR. We would be investing good amount of resources into this, would love to share our work with the main repo.
