### ISSUE TITLE
Horizontal Table Bars

### ISSUE THREAD

**Issue by vertigo-123** [implydata/pivot#195]
Hi,

I am trying to use the horizontal table bars which seems like the conditional formatting in excel. But even after updating the pivot version to 0.8.32 I am unable to find any such functionality.

Can you help me with this. Not sure my understanding is wrong here.

Thanks
Nishant

**Comment by vogievetsky** [comment]
Hi,

Could you please post a screenshot of one of your tables?

The tables bars are always on in the table:

![image](https://cloud.githubusercontent.com/assets/177816/15439155/797d7ed2-1e84-11e6-833d-0855030c92f6.png)

Here the table looks form me

**Comment by vertigo-123** [comment]
Hi,

Below is a snapshot of a table.

Let me know what's the issue
[image: Inline image 1]

**Comment by lorem--ipsum** [comment]
Hello, it seems your image wasn't added to your reply. Could you try again ?

**Comment by vertigo-123** [comment]
Hi,

I am sending it again.

Thanks

**Comment by fjy** [comment]
@vertigo-123 can you include the image?

**Comment by vertigo-123** [comment]
![pivot snapshot](https://cloud.githubusercontent.com/assets/18504031/15453003/1e73027a-2021-11e6-8bbe-8494a45c4835.PNG)

Here is the snapshot.

**Comment by fjy** [comment]
Hi, can you also include a screenshot of the "info and feedback view". You
can access this view in the burger menu to the left.

**Comment by vertigo-123** [comment]
Hey,

I am unable to see the "info and feedback view" in the left menu.

I do remember it was there earlier before we upgraded it to version 0.8.32.

Thanks
NIshant

**Comment by fjy** [comment]
@vertigo-123 are you sure on you are on 0.8.32?

**Comment by vertigo-123** [comment]
100%. the tab header also shows the same version.

Also I have one more doubt about this

   - Ability to define custom granularities for bucketing

I am not sure even if this is working. As per my understanding this should
allow me to bucket based on measures? am i right ?

**Comment by vogievetsky** [comment]
@vertigo-123 , has this been resolved or are you still facing an issue here?

**Comment by vertigo-123** [comment]
Hi,

Yes the issue has been resolved after updating the version.

Thanks
Nishant

**Comment by vogievetsky** [comment]
Cool!
