### ISSUE TITLE
Bug in displaying custom time granularities

### ISSUE THREAD

**Issue by TheMP** [implydata/pivot#197]
Hi, I spotted a bug in the way pivot handles custom granularities. I've passed a custom granularities to my time dimension in config.yaml file:

` granularities: ['PT1H','PT8H','PT12H', 'P1D','P1W']`

Everything works just fine - if I use time dimension in split row in pivot UI, I can see and select all of the granularities I've defined. 

However, when I change time filter in Filter row (to e.g. last 6H) then the time dimension is set back to be split by 5min buckets, even though I have not defined this granularity in `granularities` option

**Comment by evasomething** [comment]
Hi, this should be fixed in 0.8.38!

**Comment by TheMP** [comment]
Great, thanks!

**Comment by vogievetsky** [comment]
🎆
