### ISSUE TITLE
Client code to handle serverRoot 

### ISSUE THREAD

**Issue by khuevu** [implydata/pivot#204]
Hi, 
I try running pivot at `/serverRoot` but it is not dealt with properly. 

In Server code: 

https://github.com/implydata/pivot/blob/master/src/server/views.ts#L58

`/serverRoot/pivot.js` should be returned instead. 

For the client side, the generated pivot.js and pivot-main.js does not handle serverRoot at the moment. 

Thanks for looking into it.

**Comment by khuevu** [comment]
For the background, we use pivot behind a nginx server. Nginx only forwards requests to pivot at the configured location `/serverRoot`. Therefore, the pivot js script need to append this path prefix to api path, or use relative url if possible.

**Comment by vogievetsky** [comment]
Thank you, will fix later today.

**Comment by vogievetsky** [comment]
Should be fixed in 0.8.35
