### ISSUE TITLE
Support the actual query granularity of the datasource

### ISSUE THREAD

**Issue by nevets1219** [implydata/pivot#224]
In Pivot, we only have granularity of one minute, five minute, hourly, daily, and weekly which means we can't specify a granularity in Pivot that matches our query granularity. I tried using the next lower granularity but the timeseries shown is fairly spiky and doesn't really portray what's actually happening.

For one of our datasource, we have 10 minute query granularity with hourly segment granularity. The followings are table and timeseries from Pivot with five minute and hourly granularity:

5-minute-granularity
<img width="804" alt="five_min_granularity" src="https://cloud.githubusercontent.com/assets/116701/15979423/c1db0fd8-2f18-11e6-8424-54eda7d5531c.png">
<img width="791" alt="five_min_table" src="https://cloud.githubusercontent.com/assets/116701/15979770/ed2803e2-2f1a-11e6-8e1e-f3f7afdce105.png">

Hourly-granularity
<img width="800" alt="hourly_granularity" src="https://cloud.githubusercontent.com/assets/116701/15979707/98cd73cc-2f1a-11e6-9c79-cf96ad6bb04f.png">
<img width="805" alt="hourly_table" src="https://cloud.githubusercontent.com/assets/116701/15979789/0cf6703c-2f1b-11e6-9537-c4b6274ce9f5.png">

Please let me know if you need any other information or feel that I may be doing something wrong.

**Comment by vogievetsky** [comment]
have you tried setting **granularities** ?https://github.com/implydata/pivot/blob/master/docs/configuration.md#dimensions

try: `['PT10M', 'PT30M', 'PT1H', 'P1D', 'P1W']`

**Comment by nevets1219** [comment]
I generated a config and added what you suggested to the config:
```
      - name: __time
        title: Time
        kind: time
        granularities: ['PT10M', 'PT30M', 'PT1H', 'P1D', 'P1W']
        expression: $__time
```
Then I restarted Pivot, however I don't see the change reflected in the UI for my datasource, it's still using the 5 default granularities. Nothing strange in the logs indicating anything wrong, any thoughts?

**Comment by evasomething** [comment]
Hi, what version of pivot are you running?

**Comment by nevets1219** [comment]
@evasomething We are using 0.8.26

**Comment by vogievetsky** [comment]
Yep! @evasomething added that feature as part of 0.8.28 (https://github.com/implydata/pivot/blob/master/CHANGELOG.md#0828)

Going to close this issue as it is already fixed. Please file an issue if you experience any problem after you upgrade.
