### ISSUE TITLE
Short term filter is needed in time filter

### ISSUE THREAD

**Issue by djfwan** [implydata/pivot#237]
![screen shot 2016-06-22 at 10 14 23](https://cloud.githubusercontent.com/assets/10102134/16251586/4d016d8a-3862-11e6-8e01-33481520631d.png)

Using Druid + Pivot in realtime envirment, shorterm presets is needed.
Current presets is lacking of minute unit interval.
How about add more presets or make presets configurable for usability?

**Comment by vogievetsky** [comment]
Ideally these should be configurable
