### ISSUE TITLE
How to rearrange the measures and dimensions

### ISSUE THREAD

**Issue by vertigo-123** [implydata/pivot#239]
Hi,

Is there way to reorder the measures and dimensions in the left side panel.

Currently its take the order in the random way. Let me know if there is a way to fix this.

Thanks

**Comment by vogievetsky** [comment]
yes. the order of the dimensions and measures in the UI is driven by their order in the config. Simply rearrange them in the config. If you are not using a config have pivot generate one for you with `--print-config`
