### ISSUE TITLE
Dragging dimension from filter to split leaves item stuck in the filter section (Firefox)

### ISSUE THREAD

**Issue by dclim** [implydata/pivot#25]
You're not able to interact with any of the items in the filter row until you drag another dimension into the filter list.

![screen shot 2015-09-29 at 10 32 10 am](https://cloud.githubusercontent.com/assets/11050882/10171144/c886e6aa-6695-11e5-9f95-3d65814ea2ad.png)

**Comment by vogievetsky** [comment]
confirmed, will fix soon

**Comment by vogievetsky** [comment]
This is finally fixed in Pivot 0.8.19
