### ISSUE TITLE
Does pivot only support druid?

### ISSUE THREAD

**Issue by thbeh** [implydata/pivot#257]

**Comment by thbeh** [comment]
Can pivot be use with other columnar db e.g. Cassandra, gemfire xd, etc?

**Comment by vogievetsky** [comment]
Hi, Pivot can also be used with Druid, MySQL, Postgres, and files (loaded natively). See `pivot --help` for more info. Pivot does not support Cassandra or gemfire xd and there are currently no plans to support them in the future.
