### ISSUE TITLE
Should disable 'Filter' button when no value has been selected

### ISSUE THREAD

**Issue by dclim** [implydata/pivot#26]
I think it'd be a better user experience than the current, which allows the user to click 'Filter' and does nothing.

![screen shot 2015-09-29 at 5 00 56 pm](https://cloud.githubusercontent.com/assets/11050882/10180595/b796d630-66cb-11e5-8014-1c6f1125f666.png)

**Comment by vogievetsky** [comment]
This is fixed in the latest release :-)
