### ISSUE TITLE
Issues with generating links into pivot

### ISSUE THREAD

**Issue by eunice** [implydata/pivot#270]
Hi, I'm trying to generate links into pivot by posting to <server root>/mkurl according to here (https://github.com/implydata/pivot/blob/master/docs/generating-links-into-pivot.md) 

Each time, it's responding with our configuration information instead of a url. 

How can I troubleshoot this? Or can you let me know under which circumstances that this would happen?

**Comment by vogievetsky** [comment]
omg what?! that is so bizarre. what configuration info?
Is it responding with the HTML page (that contains a `__CONFIG__`) variable?
What version of Pivot are you running?

**Comment by eunice** [comment]
yes, I meant it's responding with the HTML page. 

I'm currently running on 0.9.10

**Comment by eunice** [comment]
when its responding with the HTML page, what does it mean? am i inputting an incorrect JSON for the POST request?

**Comment by vogievetsky** [comment]
Ok there seems to be a bug that if you input invalid JSON it gives you pack the error HTML page instead of a json friendly page. I have also updated the example a little: https://github.com/implydata/pivot/blob/master/docs/generating-links-into-pivot.md

Can you post the specifics of what you are sending and what you are getting back?

**Comment by eunice** [comment]
Hi, 

We tried to post to our host 'http://pivot.triplelift.net/mkurl' with the JSON object below.
`{
  "domain": "http://pivot.triplelift.net",
  "dataSource": "main_daily_prod_v2",
  "essence": {
    "visualization": "table",
    "timezone": "Etc/UTC",
    "filter": "$__time.in(\"2015-09-10Z\", \"2015-09-20Z\")",
    "splits": ["domain"],
    "singleMeasure": "clicks",
    "selectedMeasures": ["clicks", "total_imps", "sold_imps"],
    "pinnedDimensions": [],
    "multiMeasureMode": true
  }
}`

Instead of an error page, we still get back an html page with the __CONFIG__ variable. See below. 

`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="Data Explorer">
        <meta name="author" content="Imply">
        <meta name="google" value="notranslate">
        <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-touch-icon-57x57.png?v=0.9.10">
        <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-touch-icon-60x60.png?v=0.9.10">
        <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-touch-icon-72x72.png?v=0.9.10">
        <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-touch-icon-76x76.png?v=0.9.10">
        <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-touch-icon-114x114.png?v=0.9.10">
        <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-touch-icon-120x120.png?v=0.9.10">
        <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-touch-icon-144x144.png?v=0.9.10">
        <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-touch-icon-152x152.png?v=0.9.10">
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon-180x180.png?v=0.9.10">
        <link rel="icon" type="image/png" href="/favicon/favicon-32x32.png?v=0.9.10" sizes="32x32">
        <link rel="icon" type="image/png" href="/favicon/android-chrome-192x192.png?v=0.9.10" sizes="192x192">
        <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png?v=0.9.10" sizes="96x96">
        <link rel="icon" type="image/png" href="/favicon/favicon-16x16.png?v=0.9.10" sizes="16x16">
        <link rel="manifest" href="/favicon/manifest.json?v=0.9.10">
        <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg?v=0.9.10" color="#5bbad5">
        <link rel="shortcut icon" href="/favicon/favicon.ico?v=0.9.10">
        <meta name="apple-mobile-web-app-title" content="Pivot (0.9.10)">
        <meta name="application-name" content="Pivot (0.9.10)">
        <meta name="msapplication-TileColor" content="#0093E2">
        <meta name="msapplication-TileImage" content="/favicon/mstile-144x144.png?v=0.9.10">
        <meta name="msapplication-config" content="/favicon/browserconfig.xml?v=0.9.10">
        <meta name="theme-color" content="#ffffff">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1">
        <title>Pivot (0.9.10)</title>
    </head>
    <body>
        <div class="app-container"></div>
        <script>var __CONFIG__ = {"version":"0.9.10","user":null,"dataSources":[{"name":"main_daily_prod_v2","title":"Main Daily Prod V2","engine":"druid","source":"main_daily_prod_v2","subsetFilter":null,"introspection":"none",
"dimensions":[{"name":"__time","title":"Time","expression":{"op":"ref","name":"__time"},"kind":"time"},{"name":"ad_format","title":"Ad Format","expression":{"op":"chain","expression":{"op":"ref","name":"creative_library_id"},"actions":[{"action":"lookup","lookup":"ad_format_lookup"},{"action":"fallback","expression":{"op":"literal","value":"Image"}}]},"kind":"string"},{"name":"advertiser","title":"Advertiser","expression":{"op":"chain","expression":{"op":"ref","name":"advertiser_id"},"actions":[{"action":"lookup","lookup":"advertiser_lookup"},{"action":"fallback","expression":{"op":"literal","value":"unknown"}}]},"kind":"string"},..............],"maxTime":{"time":"2016-06-30T11:00:00.000Z","updated":"2016-06-30T15:29:29.367Z"}}],"linkViewConfig":null,"customization":null};</script>
        <script charset="UTF-8" src="/pivot.js?v=0.9.10"></script>
    </body>
</html>
`

Are we missing anything in the body of the POST request? Do we need to make any modifications to our config.yaml file to get the result?

**Comment by vogievetsky** [comment]
Thank you for the detailed info. It looks like Pivot is getting a 404 on the `/mkurl` route and redirecting you to `/` the HTML you see is the Pivot page itself. I just went to http://pivot.triplelift.net/ and it appears to be behind a ngix proxy with basic auth - I wonder if that has something to do with it.

Were you posting to http://pivot.triplelift.net/mkurl or to the internal IP of that machine? did you include a basic auth header on your post?

**Comment by eunice** [comment]
I was posting to http://pivot.triplelift.net/mkurl and I did include a basic auth header. 

What do you mean by Pivot is getting a 404 on the `/mkurl` ? It means
