### ISSUE TITLE
Pivot should be able to properly introspect schemas with hyperUnique measures

### ISSUE THREAD

**Issue by turu** [implydata/pivot#278]
Pivot does a really good job introspecting Druid datasources. However, it fails to correctly detect that a measure is of type hyperUnique. This means that we need to provide separate configuration for datasources using hyperUnique measures. This makes it very tedious to handle large number of data sources and requires additional orchestration on the side of a developer. 

It would be great if Pivot was able to handle this case automatically. If this can't be done simply by using metadata exposed by Druid, then perhaps Pivot could try to guess that a measure is of type hyperUnique, when it fails to do a sum over it, rather than propagate this error to the end-user.

Is there any specific issue preventing us from fixing this?

**Comment by gianm** [comment]
@turu which version of Pivot and Druid are you using? I just tried this with IAP 1.3.0 (Pivot 0.9.10, Druid 0.9.1.1) and introspection of hyperUniques worked for me without any special config.

**Comment by turu** [comment]
Currently we are using Pivot 0.9.14 and Druid 0.8.0. Should an upgrade of Druid help?

**Comment by gianm** [comment]
Upgrading Druid should definitely help. There have been a lot of metadata-related fixes and additions since 0.8.0 and some of them are necessary for hyperUnique introspection to work.

**Comment by turu** [comment]
Ok, good to know. We must upgrade then.

**Comment by gianm** [comment]
@turu Please re-open if you still see an issue with the latest Druid.
