### ISSUE TITLE
Resize dimensions/measures lists

### ISSUE THREAD

**Issue by gianm** [implydata/pivot#279]
By default the measures list is quite small if you have a lot of dimensions (just 4 measures). It'd be nice to be able to resize that for situations where I'm changing measures frequently but not using the dimension list frequently. Especially if I only have 8 measures or so – I'd like to see them all at once to avoid scrolling.

**Comment by sambitdixit** [comment]
This is indeed a genuine need from usability prospective.

**Comment by vogievetsky** [comment]
This has been added, get the latest from https://imply.io/get-started
