### ISSUE TITLE
defaultSplits Flag is not Working Anymore

### ISSUE THREAD

**Issue by alodium** [implydata/pivot#282]
Hi.

We noticed that since version 0.9.0 (commit faa86d02192f17e159e53838c9539a519bb81e34 )
The flag for default filters stoped working.
Fast tracking showed that the change of the options object to null (https://github.com/implydata/pivot/blob/master/src/common/models/data-source/data-source.ts:661) caused this bug.

Commenting it out fixed the problem, but I could not understand what was the reason of nulling the options at this stage.

Can you confirm? Also, why is the null there, if you care to explain.

Thanks!
Lior.

**Comment by vogievetsky** [comment]
That was an oversight and a mistake.

The point of nulling the options is that it is all server crap and there is no need to send it to the client.
Why would the client want to know about the exact nature of the custom attributes (which can be huge).

I forgot that defaultSplits lived in also I thought they moved to be on dataSource itself.

Will fix and add a test. Thank for spotting the issue.

**Comment by vogievetsky** [comment]
This should be fixed now (sorry forgot to update the issue)

**Comment by alodium** [comment]
We already saw and can confirm. 
Thank's guys! Great job.
