### ISSUE TITLE
Specifying measures that pivot doesn't know about

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#3]
There are some times where people might add an aggregator to Druid that pivot doesn't necessarily know about.  For those cases, it would be really nice if the druid config could have an extra field on a measure that allows you to specify the exact json you want to send for the aggregator.

This method of solving the problem would expose complete flexibility to extend and use pivot on extensions.

The other option I can imagine would be to expose the grammar/setup for measures as a thing that is extendable in pivot, so that I could then define it there.

**Comment by vogievetsky** [comment]
Added custom aggregators. This is now in master.
https://github.com/implydata/pivot/blob/master/config_sample.yaml#L194

Try it out.
