### ISSUE TITLE
Query Error: Instantiation of [simple type, class io.druid.query.topn.TopNQueueValue failed

### ISSUE THREAD

**Issue by nishantmonu51** [implydata/pivot#308]
Steps to reproduce with wikiticker dataset - 
1) Add split on time and create line chart 
2) Add split on dimension isRobot 
3) Add a filter dimension on isRobot select value - true
Attached snapshot. 
<img width="666" alt="screen shot 2016-07-27 at 9 29 40 pm" src="https://cloud.githubusercontent.com/assets/5023786/17182504/4f37c0b8-5441-11e6-9d30-a1f8dc22c104.png">

**Comment by turu** [comment]
I am able to reproduce this reliably on all our datasets.
