### ISSUE TITLE
Search Dimension

### ISSUE THREAD

**Issue by venukb** [implydata/pivot#32]
Today when we use dimension in a filter, it shows a list of values. However often one needs to search for a specific value.
Druid enables search via `http://druid.io/docs/0.8.1/querying/searchquery.html`

Is this something in pivot's roadmap?

**Comment by vogievetsky** [comment]
Yep this is on the roadmap.

**Comment by gianm** [comment]
:+1: would be sweet!

**Comment by vogievetsky** [comment]
There is now search in the filter menu :-)

**Comment by venukb** [comment]
Awesome. Thanks :+1:
