### ISSUE TITLE
Multiline graph from config.yaml

### ISSUE THREAD

**Issue by satanworker** [implydata/pivot#322]
Hello!

I really need to understand if its possible to aggregate few measures into one multiline graph by expression in config.yaml of my Pivot? 

So I have those 2 dimensions, like "dimension1" and "dimension2", and I need something like: 
     - name: combine
        title: Combine
        formula: [$main.sum($dimension1), $main.sum($dimension2)]

I've tried writing custom aggregation with no luck. Is it even possible to make this kind of feature from config.yaml or I need to go inside of Pivot? What I need to get in result is something like Split graph, where we have few lines on one graph, but just showing diffirent measures instead of filter split.

If I have to modify Pivot's sources in my case, could you please point me the direction where to start looking?

Thanks in advance!

**Comment by vogievetsky** [comment]
Hi this is not possible in general right now. Can you add some details as to your use case? What are the two formulas you are trying to show?
