### ISSUE TITLE
Export to CSV on Totals view

### ISSUE THREAD

**Issue by ayxos** [implydata/pivot#323]
If on Pivot a user is switching from "Line-chart" or "Table" view to "Totals" view, there is still the chance to download a CSV with the previous data.

<img width="353" alt="screen shot 2016-08-04 at 12 36 09" src="https://cloud.githubusercontent.com/assets/3403938/17398998/13c2435a-5a40-11e6-9efe-8c1614508eab.png">

So, to fix it, in **totals.tsx** (_./src/client/visualizations/totals/totals.tsx_) line: 74
The value "registerDownloadableDataset" is keeping the previous value.
Export to CSV functionality on "Totals" view should be null in order to not download wrong data.

```
precalculate(props: VisualizationProps, datasetLoad: DatasetLoad = null) {
    const { registerDownloadableDataset, essence } = props;
    const { splits } = essence;

    var existingDatasetLoad = this.state.datasetLoad;
    var newState: BaseVisualizationState = {};
    if (datasetLoad) {
      // Always keep the old dataset while loading
      if (datasetLoad.loading) datasetLoad.dataset = existingDatasetLoad.dataset;

      newState.datasetLoad = datasetLoad;
    } else {
      datasetLoad = existingDatasetLoad;
    }

    var { dataset } = datasetLoad;
    if (registerDownloadableDataset) {
      registerDownloadableDataset(dataset && splits.length() ? dataset : null);
    }

    this.setState(newState);
 }
```

Here the view is checking if there are dataset and splits and if not, reseting the downloadable dataset.

**Comment by vogievetsky** [comment]
Huh, will take a look.
