### ISSUE TITLE
List of dimension and measure not shown on Safari

### ISSUE THREAD

**Issue by acslk** [implydata/pivot#325]
When using pivot on OS X safari, dimension and measure columns are empty.

This can be reproduced with almost all data sources on latest.imply.io.

**Comment by evasomething** [comment]
Hi! Do you mean on the left panel? I'm having trouble reproducing
![image](https://cloud.githubusercontent.com/assets/4262235/17417438/370fd702-5a48-11e6-9083-ea7e348d7bc4.png)

**Comment by acslk** [comment]
that's strange, here's my screenshot
![screen shot 2016-08-04 at 1 56 42 pm](https://cloud.githubusercontent.com/assets/11131839/17418076/6b5475f6-5a4b-11e6-8aa2-7b0156c42ee3.png)

**Comment by acslk** [comment]
just updated safari from 8.0.8 to 9.1.2 and everything seems good

**Comment by vogievetsky** [comment]
Crazy!
