### ISSUE TITLE
Specific time selection with hour and minute granularity

### ISSUE THREAD

**Issue by himanshug** [implydata/pivot#330]
Currently we can only filter for specific days and then select specific time-slice on timeseries display . That requires us to send a query for whole day for no reason and also forces to get a timeseries visualization for time slice selection even if we want just ta table in the end.

**Comment by vogievetsky** [comment]
more advanced filtering options are in the pipeline

**Comment by vogievetsky** [comment]
this is related to #181

**Comment by himanshug** [comment]
duplicates #181
