### ISSUE TITLE
thenify-all node dep is dead

### ISSUE THREAD

**Issue by ayxos** [implydata/pivot#339]
It is not possible install pivot because a external dependency is not answering 

```
npm ERR! fetch failed http://registry.nodejitsu.com/thenify-all/-/thenify-all-1.6.0.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! fetch failed http://registry.nodejitsu.com/thenify-all/-/thenify-all-1.6.0.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! fetch failed http://registry.nodejitsu.com/thenify-all/-/thenify-all-1.6.0.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ECONNRESET

npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marco/projects/pivot/npm-debug.log
```

**Comment by typpo** [comment]
Noticed this as well.  It's because `thenify-all` in `npm-shrinkwrap.json` points to `registry.nodejitsu.com`, which is **down**.  Every other package points to the canonical registry, `registry.npmjs.org`.

Workarounds: manually replace `nodejitsu.com` with `npmjs.org`, or just delete `npm-shrinkwrap.json`.

**Comment by vogievetsky** [comment]
Thank for fixing this. We were struggling with it also in https://github.com/implydata/pivot/pull/338
Not sure why shrinkwrap picked nodejitsu for that one package but I made it so that will never happen again.

**Comment by pjain1** [comment]
@vogievetsky When you are you planning to get this commit in a new release. Is it possible to do it soon ?

**Comment by alodium** [comment]
@pjain1 just change the url of 
http://registry.nodejitsu.com/thenify-all/-/thenify-all-1.6.0.tgz
in the file shrinkwrap.json
to http://registry.npmjs.org/thenify-all/-/thenify-all-1.6.0.tgz

**Comment by pjain1** [comment]
@alodium Thanks for the suggestion. However, we do not deploy pivot directly ... we wrap pivot in another node app for reasons related to how our internal infrastructure works. Probably I can create a shrinkwrap file in the outer app and change the url for thenify-all dependency, that might work but given pivot is released frequently I might just wait for the new release if it is not too far.
