### ISSUE TITLE
Regex query support.

### ISSUE THREAD

**Issue by djfwan** [implydata/pivot#347]
Druid support regex query. 

But Pivot doesn't support.

If regex query support on Pivot, it it very very powerlful.

Thanks.

**Comment by evasomething** [comment]
Hi! This will be out soon

**Comment by djfwan** [comment]
Good!!

**Comment by evasomething** [comment]
Hi! This is out in pivot 0.9.37
![image](https://cloud.githubusercontent.com/assets/4262235/17791176/c53f7986-654e-11e6-851a-02db8e210549.png)
