### ISSUE TITLE
nodejitsu - connection refused

### ISSUE THREAD

**Issue by venukb** [implydata/pivot#350]
With the latest code (SHA 799d3f932ace48d5f0a40985bcb1c67da3eac61b), we are seeing this

```
npm ERR! fetch failed http://registry.nodejitsu.com/thenify-all/-/thenify-all-1.6.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ECONNREFUSED
```

looks like this was found and fixed in 181766a11cc67d781659e76d609c6be098221d98, but still see this error.

**Comment by evasomething** [comment]
Hi! this was indeed fixed in 181766a but has not been published yet

**Comment by evasomething** [comment]
am assuming you're trying to install pivot through npm but please let me know if I'm mistaken!

**Comment by venukb** [comment]
yes. I was trying via npm route.

**Comment by vogievetsky** [comment]
nodejitsu fully dumped in imply-pivot@0.9.37
