### ISSUE TITLE
Removed datasources are still displayed

### ISSUE THREAD

**Issue by chtefi** [implydata/pivot#354]
Hey,

I removed some datasources and they were still displayed on the home screen of Pivot. I waited a bit and check the coordinator, they were really gone. If you click on them in Pivot: "Query error: no such datasource". I guess there is some sort of cache in Pivot that never checks if the datasources still exists when it's updated.

Workaround: restart Pivot.

Thanks,

PS: Pivot is really great.

**Comment by vogievetsky** [comment]
Hi, this is how it is expected to work right now. DataCubes (aka data sources) are auto added but never auto removed. You ether have to restart Pivot, and if you have a config you will have to delete them from there also. We are working on fixing that and making that system a lot better literally right now.

**Comment by chtefi** [comment]
All right @vogievetsky, thanks. Do you want I close this issue if it's already wip ?
