### ISSUE TITLE
Input for datetime filter doesn't work correctly on Firefox

### ISSUE THREAD

**Issue by dclim** [implydata/pivot#36]
Can't select, clicking on the element always puts the cursor on the left edge. I don't see this issue with Chrome.

![screen shot 2015-10-08 at 12 07 14 pm](https://cloud.githubusercontent.com/assets/11050882/10375363/58e5da5a-6db5-11e5-94fd-d97c69450158.png)

**Comment by vogievetsky** [comment]
Looking into it!

**Comment by dclim** [comment]
This looks fixed to me, thanks Vad!
