### ISSUE TITLE
Dimensions case sensitivity problem at schema discovery

### ISSUE THREAD

**Issue by vvararu** [implydata/pivot#368]
Hi,

I have  a problem while auto-discovering source schema:

`Fatal settings load error: duplicate dimension name 'testdimension' found in data cube: 'mydatasource'`

I have observed that in the ingested data we have both dimensions 'testdimension' and 'testDimension'. Is that a problem? Isn't pivot case sensitive?

Thanks, Vadim.

**Comment by l15k4** [comment]
Hey,

is there a workaround? I'm facing the same problem https://groups.google.com/forum/#!topic/imply-user-group/8s0ze-nmgCI
