### ISSUE TITLE
Question: Is it possible to embed pivot in existing application

### ISSUE THREAD

**Issue by sipte** [implydata/pivot#369]
I am trying to figure out if I can embed pivot in my existing app as a tab, has anyone done it

**Comment by lubomirmatus** [comment]
Hi, we are also interested in this feature.

We would like to embed predefined charts into out webapp. We can capture chart definition json from pivot `register` request (`{"essence":{"dataCube":"db", ...`).

Our proposal is to implement interface for this use-case taking all necessary data from url parameters and request headers. The chart definition json can be passed in url the same way as SQL query is passed in SQL part of pivot (compressed using lzstring and encoded into base64). Also the login screen needs to be bypassed with credentials included in `Authorization` http header. The ui mode should be reduced, with chart only, with no header and no side panels.

Something like: `http://host/pivot?embedded_chart=<data>`.
