### ISSUE TITLE
Past hour not immediately clear whta the time range is

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#4]
When looking at past hour, the filter displays just the hour that is being used.  Which makes sense, when I think about it, but I had to actually try changing to 6 hours first and then I finally thought about it and realized what it was doing.

I think it would be simpler for the user if it showed 5:00 - 6:00 or whatever.

**Comment by vogievetsky** [comment]
Working on this :-)

**Comment by vogievetsky** [comment]
This is done.
