### ISSUE TITLE
Time range selectors (past 1/6/24 hours, current day, etc.) does not have the correct ending date

### ISSUE THREAD

**Issue by dclim** [implydata/pivot#40]
All of them are giving me a date in the past instead of till now, Chrome and FF.

![screen shot 2015-10-12 at 10 28 12 am](https://cloud.githubusercontent.com/assets/11050882/10433026/2ff5323e-70cc-11e5-88af-f4c660ae725e.png)

**Comment by vogievetsky** [comment]
I am happy to report that this is fixed now. The config now supports a `refreshRule` parameter and internally time is not assumed to be static.
