### ISSUE TITLE
If the pivot can support other timezones besides UTC?

### ISSUE THREAD

**Issue by wangmuling** [implydata/pivot#41]
The pivot is only support UTC timezone currently,I hope it could support other timezones,such as Asia/Shanghai.Thanks!

**Comment by vogievetsky** [comment]
Hi. experimental timezone support has beed added to Pivot. See here for an example: https://github.com/implydata/pivot/blob/master/config.yaml.sample#L43

This is still very experimental and there are a few bugs where UTC (instead of the selected timezone) is used for display, will fix.

**Comment by wangmuling** [comment]
ok.Thanks vogievetsky.Can I post you to solve the bugs where UTC is userd for display priority?

**Comment by westerly** [comment]
Hi. I have tried this new feature! 

Here is my feedback (I have tried with America/Los_Angeles time zone):

It looks like it's working for the time series graph. Although for some reason when I do a zoom on my graph, pivot doesn't display anything. I don't see this behavior when using UTC.

On the tables however, the time dimension is still displayed in UTC (Only on the table, the filter time range is in the correct time zone).

Also it doesn't seem possible to specify a default time zone in the config file for all the data sources. I think it would be useful to have this possibility.

Guillaume

**Comment by maximenay** [comment]
Hey,

If Pivot could support different time zones, it would greatly help us democratize its usage within our company. Right now, some of the bugs that westerly outlined prevent us from sharing Pivot with our business people.

**Comment by vogievetsky** [comment]
Latest Pivot release (0.8.22) comes with a timezone selection UI and comprehensive timezone support.

**Comment by maximenay** [comment]
Great!
