### ISSUE TITLE
Filter lock on sorting is a bit jarring

### ISSUE THREAD

**Issue by gianm** [implydata/pivot#44]
This flow is a bit jarring:

1) Split on a dimension to get a table
2) Click on a row to get a temporary filter thingy
3) Click on a column header to change the sort
4) Now the temporary filter is locked in

I think it would be less jarring if the filter stayed a temporary filter.

It's possible that changing the sort means the row is no longer be in the top X, in which case I guess two things could happen?
- it could stay a temporary filter even though the row is no longer visible
- it could not be a filter anymore

I _think_ the first one would be better but I'm not sure

**Comment by asherbitter** [comment]
Good point!
