### ISSUE TITLE
When using --example, --config is ignored

### ISSUE THREAD

**Issue by pdeva** [implydata/pivot#45]
I want to run the wiki example, but i want pivot to start on port 8080 instead of 9090.
However, it seems to ignore the --config option when --example is passed

**Comment by vogievetsky** [comment]
That is correct the --config is ignored if --example is used. I can see how that would be annoying if you are using the `port: 8080` in the config. As a current workaround you can do: `pivot --example wiki --port 8080` from the command line but I'll make the config work as well.
