### ISSUE TITLE
Configurable default time period

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#5]
It would be really cool to have a configurable default time period in the config.yaml.  This is something I'd want to set on a per data-source basis, I think.

A suggestion/request for how to set it would be to take an ISO8601 Duration, so like, I could set `PT5m` or `PT1h` or `P1d` and it would automatically generate `<duration I specified>/<maxTime()>`

**Comment by vogievetsky** [comment]
+1 this is coming soon.

**Comment by vogievetsky** [comment]
This is done (in 0.2.10)
https://github.com/implydata/pivot/commit/d2cae99670d7f174adcd1b1a8e15bf1b7b8c0296
Use `defaultDuration: P1D` / `defaultDuration: PT1H` or whatever
