### ISSUE TITLE
Battle-harden Pivot against DDoS attacks

### ISSUE THREAD

**Issue by milimetric** [implydata/pivot#53]
Opening this for @vogievetsky and me.  We want to track progress on Pivot's ability to run on a public website without allowing malicious DDoS attackers to bring down the data stores Pivot targets.

**Comment by vogievetsky** [comment]
Working on this. There are a few things that need to be added for that to work. We plan on putting some public demos out so this is a high priority.

**Comment by milimetric** [comment]
It's not a high priority for us by any means, so no pressure from me.  Just wrote it up so we can track progress.

**Comment by vogievetsky** [comment]
Yep. That is how open source should work. Will be hardening Pivot and updating here.
