### ISSUE TITLE
Improve filter bar menu thingy's choice of metric

### ISSUE THREAD

**Issue by gianm** [implydata/pivot#56]
The menu you get for a dimension in the filter bar (the one that has the checkboxes and the search bar and all that) appears to just use the first defined metric for its sorting. There are a couple of problems:

1. It's actually not clear which metric is being used as there is no label or other visual indicator
2. Once you do figure out what metric is being used, there doesn't seem to be a way to change it to something better (if the first metric is not what you want)

**Comment by vogievetsky** [comment]
Ok well at least one of those we can fix very easily.

**Comment by gianm** [comment]
will you share which one? :)

**Comment by vogievetsky** [comment]
Solved 1 and 2 :-p
