### ISSUE TITLE
Export Functionalities

### ISSUE THREAD

**Issue by geo1211** [implydata/pivot#57]
it'd be useful to be able to export the raw data we see on pivot
- [ ] totals
- [ ] table

Also exporting charts would also be very useful:
- [ ] time series
- [ ] bar chart
- [ ] geo visualization

**Comment by curran** [comment]
I'm curious, what format would you want to export the chart in?

**Comment by geo1211** [comment]
the common image formats i suppose... jpg, bmp,... etc.

**Comment by asherbitter** [comment]
Hi - there is no timeline for this at the moment, but this is definitely something we want to build. Especially the data export.

**Comment by vogievetsky** [comment]
Data export would be easy to do.

**Comment by ashishawasthi** [comment]
Data (e.g. CSV) export that have a larger limit than what is on UI will be very useful. Say if UI is showing top 100, but CSV export has top 10,000 (a custom limit) records.

**Comment by JoarSvensson** [comment]
I vote for data export in Pivot as well. Really handy to have. To start with, just exporting what you can see in the UI would be good.

**Comment by code-artisan** [comment]
> Data export would be easy to do.

Perfect, what time do you finish this functional? I am waiting for this. :smiley:

**Comment by mattallty** [comment]
+1, would be a great feature !

**Comment by aiccha** [comment]
Is there any timeline for this feature?  It would be pretty useful.

**Comment by kastsiushkin** [comment]
+1, also awaiting for this feature

**Comment by emtiazahmed** [comment]
:+1:

**Comment by abhs50** [comment]
:+1:

**Comment by vogievetsky** [comment]
this is coming soon.

**Comment by solarix888** [comment]
+1 would love to see this feature, any timeline?

**Comment by asherbitter** [comment]
REALLY SOON

**Comment by giorgosera** [comment]
+1 looking forward to this feature

**Comment by vogievetsky** [comment]
![image](https://cloud.githubusercontent.com/assets/177816/14724652/608615e8-07cc-11e6-9c95-152f0dbed318.png)

Export to CSV was added in Pivot 0.8.15. Happy to close this issue 🎆

**Comment by solarix888** [comment]
👏

**Comment by geo1211** [comment]
👏👏👏👏👏

**Comment by ashishawasthi** [comment]
:gem:

**Comment by code-artisan** [comment]
💯
