### ISSUE TITLE
Display druid query

### ISSUE THREAD

**Issue by mattallty** [implydata/pivot#58]
It would be very usefull to be able to display the resulting Druid Query generated by pivot.

**Comment by asherbitter** [comment]
Agree, makes a lot of sense. Also, Plywood and PlyQL versions of the query could be nice.

**Comment by vogievetsky** [comment]
Agree. @asherbitter PlyQL does not factor into it.

**Comment by asherbitter** [comment]
Silly me.

**Comment by vogievetsky** [comment]
Ops I just noticed that this is still open. For a very long time now Pivot has supported a --verbose (-v) command line option that will show you all queries made to Druid.

**Comment by mattallty** [comment]
Sorry for the misunderstanding, but the idea of this suggestion was *not* to have to have server-side access to display the query. The idea was to have a small button or pic that can be clicked to display either the "raw" druid query, or something like the "curl" command equivalent to replay the query form elsewhere.

**Comment by asherbitter** [comment]
It's not on the roadmap at the moment - but reopening.
