### ISSUE TITLE
Date picker is difficult to manually edit

### ISSUE THREAD

**Issue by gianm** [implydata/pivot#59]
If you click on the date picker and try to edit it, sometimes it rejects your edits and resets the time. For example this happens to me,

1. I want to change the day of a query
2. I click after the day part of the datetime to put the insertion point there
3. I delete it and start typing a new day
4. The picker resets itself to 1970-01-01 00:00

Things seem to work if I delete the time before changing the date, but I don't think I should have to do that.

**Comment by vogievetsky** [comment]
I feel your pain brother.

**Comment by vogievetsky** [comment]
Latest Pivot release (0.8.22) comes with a date picker UI and comprehensive timezone support.
