### ISSUE TITLE
Ability to compare multiple selections in on graph

### ISSUE THREAD

**Issue by alexrovner** [implydata/pivot#60]
Allow the user to pick a few values from a dimension and graph the results.

**Comment by vogievetsky** [comment]
Working on this.

**Comment by vogievetsky** [comment]
I am happy to announce that Pivot 0.6 just shipped and its flagship feature is the new overlay compare:

![image](https://cloud.githubusercontent.com/assets/177816/11378790/de80efe0-92a1-11e5-8c4a-bcdb8b844644.png)

**Comment by alexrovner** [comment]
Thank you very much for this feature, we can't wait to try it out.
