### ISSUE TITLE
Ability to compare with historic data

### ISSUE THREAD

**Issue by alexrovner** [implydata/pivot#61]
Enable the user to compare / chart current timeline vs historic. Today vs yesterday etc.

**Comment by asherbitter** [comment]
Would definitely be great. No timeline for it at the moment.

**Comment by giorgosera** [comment]
:+1: this will be super useful.

**Comment by alodium** [comment]
Hi.

We implemented such a feature with full control and time comparison selection, in the graphs and in the pinboard, include calculation of deltas and such.

Currently, we are QAing this feature and checking for the best way to contribute it back to the Pivot project. Hope to be able to do this soon.
@cybermarkus1

**Comment by giorgosera** [comment]
@alodium do you have a fork with this functionality we can check out? 

I'd love to see this feature implemented.

**Comment by alodium** [comment]
@giorgosera - the plan is to contribute it to this project in late June / July.

**Comment by giorgosera** [comment]
thanks @alodium looking fwd to seeing this implemented.

**Comment by mindis** [comment]
Hi @alodium, would you be able to share the time comparison feature?

**Comment by alodium** [comment]
Hi All - Since this project is no longer under the same license, sadly, we cannot contribute our code. Sorry.
Thanks.

**Comment by mindis** [comment]
Hi, would it be possible to contribute this feature to Apache 2 licensed fork Swiv https://github.com/yahoo/swiv
