### ISSUE TITLE
Dataset access controls

### ISSUE THREAD

**Issue by alexrovner** [implydata/pivot#62]
Would be nice to have the ability to restrict datasets the user is allowed to view

**Comment by vogievetsky** [comment]
Pivot does not currently have a concept of user. Pivot was designed to be impeded within a user management system that you provide. This is what we are going internally at imply.

Adding "user" to Pivot is not (and will likely never be) on the roadmap. This is still very useful feedback and I would appreciate if you could expand on what you need as we might in the future release a project to specifically solve that problem.

At present, If you have several types of users that have different access permissions, say Admins and Account Managers the **simplest** thing would be to run two instances of Pivot with different configs that have access to different datasources and then maybe putting them in different VPNs or proxying them from your existing user management system

One potentially useful feature that is going to be released this week is subset filtering. Where you could define a data source in Pivot but have it restricted to a specific hidden filter (invisible to the users). So say you have a Druid datasource of sales, you could restrict it to `$country == 'USA'` and the users of Pivot will never be able to access data outside of that filter.

**Comment by fjy** [comment]
One additional comment is that Pivot is very much designed to be embedded in other applications, so if someone were to create a login/admin system, Pivot could be easily included. Also, subset filtering has been shipped.

**Comment by giorgosera** [comment]
@fjy can you elaborate on "embedded in other applications"? Are there any examples?

**Comment by sambitdixit** [comment]
Is there a possibility to inject the config.yaml not from a File rather from a URL (REST endpoint). In that case i can dynamically manage the configs from the REST service layer and pivot should just leverage it from there. But only catch will be - will pivot be able to read the configs dynamically something like property change listener.

**Comment by lc-rezende** [comment]
Is it possible to dynamically use the subset filter formula? I use LDAP as the access mechanism and it would be great if I could get the logged user name and filter my cube based on that.
