### ISSUE TITLE
Ability to download data to CSV / Excel

### ISSUE THREAD

**Issue by alexrovner** [implydata/pivot#63]
Provide the ability to download the current view / table into CSV file.

**Comment by vogievetsky** [comment]
This is similar to https://github.com/implydata/pivot/issues/57 . This is in the works but not super high priority, focusing on finishing some core features first.

**Comment by tommyogp** [comment]
:+1: even better to have PDF

**Comment by Chloe-Pignier** [comment]
+1

**Comment by mattallty** [comment]
+1 !

**Comment by aiccha** [comment]
Is there any timeline for this feature?

**Comment by vogievetsky** [comment]
Export to CSV was added in Pivot 0.8.15.
