### ISSUE TITLE
value mapping on display

### ISSUE THREAD

**Issue by geo1211** [implydata/pivot#68]
many dimensions are stored/processed as IDs instead of their actual names for obvious performance/storage reasons - would be great if there's a way to specify where to look up those values on display

such as 
1 -> MSN
2 -> NY Times

in either multiple database tables, or flat files, as different columns' IDs could be the same but map to diff values

**Comment by vogievetsky** [comment]
This is a very important feature. It is on the near term roadmap.

**Comment by geo1211** [comment]
label: coming soon?

**Comment by vogievetsky** [comment]
This is now possible using the newly added `.lookup(...)` function see here: https://github.com/implydata/pivot/blob/master/config.yaml.sample#L201 for an example
