### ISSUE TITLE
Disable introspection of non configured sources

### ISSUE THREAD

**Issue by venukb** [implydata/pivot#69]
I have around 13 datasources in Druid and have configured 7 of them in config.yaml with introspection set to `none`

On startup, see this 
`Initial introspection complete. Got 13 data sources, 7 queryable`. 6 of the other data sources are for test and don't intend to configure/query them.
However pivot, keeps trying to query/introspect. These messages are dumped periodically

`Getting the latest MaxTime for {datasource}`
`Failed to introspect data source:  ... `

How to tell pivot to just use the data sources defined in config.yaml

**Comment by vogievetsky** [comment]
Yep, I want to add that. FYI `introspection: none` will not do anything here as that is for the datasources themselves.

**Comment by vogievetsky** [comment]
Hi. Pivot 0.6.x has just been released. You can now add `sourceListScan: disable` to the top level of your config and new datasources that are not in the config will not be automatically added.

Marking the issue as closed. Please reopen if you find problems.
