### ISSUE TITLE
Configurability of "default" view for a data source

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#7]
The config exposes the ability to describe the data source as best as possible right now, which is great.  It doesn't provide the most configurability for the "default view" on a data source.  For different use cases it can be nice to have different "default" views, so that would be something that I would probably want in the config.

Some ideas are like:

1. default filters
2. default splits
3. default dimension pinnings
4. default time window

etc.

**Comment by vogievetsky** [comment]
3 and 4 are done.

**Comment by vogievetsky** [comment]
added support for defaultFilter (1) not going to do default splits (2) in the coming time because it has UI and implementation complexities [wont fix]. Closing the ticket.
