### ISSUE TITLE
5m, 10m, 15m time split granularities

### ISSUE THREAD

**Issue by gianm** [implydata/pivot#71]
These are really useful for metrics data that is noisy at the minute level but too coarse at the hourly level.

**Comment by asherbitter** [comment]
Good point!

**Comment by curran** [comment]
I suppose for completeness 30m should also be there.

I agree this seems like it would be useful. Here's one example case where the 1m data is very noisy, but the 1h level might be too coarse: [![](http://bl.ocks.org/curran/raw/320c765d77cbb5b37e08/thumbnail.png)](http://bl.ocks.org/curran/320c765d77cbb5b37e08)

**Comment by vogievetsky** [comment]
Added 5M

**Comment by asherbitter** [comment]
I believe the idea is, 5 minutes for now since 1min to 1hour was by far the largest gap. At some points we should probably think about a way to make it more flexible.

**Comment by evasomething** [comment]
Hi! pivot v0.8.28 allows you to define a list of 5 granularities you want to use

https://github.com/implydata/pivot/blob/master/docs/configuration.md#dimensions
