### ISSUE TITLE
Hardcoded Limits 

### ISSUE THREAD

**Issue by nkaul** [implydata/pivot#72]
When you split the data based on a specific dimension, the max number of rows you can see in hardcoded to 100, which is really limiting. There is also no pagination to actually go through rest of the data.  
 Can this be updated to "all data"  and  a "user-editable" limit and rows displayed  per page(implementation of some sort of data pagination)  

<img width="830" alt="screen shot 2015-11-30 at 4 41 45 pm" src="https://cloud.githubusercontent.com/assets/2053951/11485606/2a27b980-9782-11e5-9f17-f8d1dea3bbe6.png">

**Comment by asherbitter** [comment]
Good points! These are definitely things we are looking to improve, although there is no timeline for it at the moment.

**Comment by spspaul** [comment]
Please consider some of the [things discussed in this thread](https://groups.google.com/forum/#!topic/imply-user-group/Of1rm-H5YCU) as well.  Thanks.
