### ISSUE TITLE
Config variable for request timeout

### ISSUE THREAD

**Issue by vvararu** [implydata/pivot#75]
Is it possible to provide a configuration variable for the request timeout? 30 seconds is really much for a druid cluster, but sometimes there may be cases where it's needed.

Thanks.

**Comment by vogievetsky** [comment]
Sure, we can add this, it should definitely be there. It should exist.

**Comment by vogievetsky** [comment]
If you install the latest pivot you can now add: `timeout: 60000` to change the timeout to, say, 60 seconds (the number is in ms)

**Comment by vvararu** [comment]
Hi Vadim,

Could you please add it in sample config.yml? At which level should i add the param?

**Comment by vvararu** [comment]
I've found. We should put it at the top level of the yaml file.
