### ISSUE TITLE
Cancelling timeouted queries

### ISSUE THREAD

**Issue by vvararu** [implydata/pivot#76]
Hi Vadim,

As I've understood, technically it's possible to cancel a running druid query. I think it would be great to cancel the query in case of timeout.

What do you think about that?

**Comment by vogievetsky** [comment]
It is actually possible to forward the timeout parameter to Druid via the context (http://druid.io/docs/latest/querying/query-context.html) and have Druid auto cancel the queries.
Pivot should 100% be doing that.
