### ISSUE TITLE
Filter on a single value hides the value

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#8]
When I have a filter on a single dimension, the thing that shows up in the Filter portion of the view just shows me `dimension_name (#)`.  Which makes sense if I don't have enough screen real-estate to show the value.  If I do have enough screen real-estate, I'd really like to be able to see the value.

**Comment by fjy** [comment]
+1 I have trouble with this one as well

**Comment by vogievetsky** [comment]
Changed how single value work.
