### ISSUE TITLE
Mathematical functions in Druid post-aggregation

### ISSUE THREAD

**Issue by msspadoni** [implydata/pivot#83]
It would be useful to have the possibility to define post-aggregation for queries, in which to use mathematical functions like SQRT(), to let be evaluated the standard deviation having stored the variance.

**Comment by vogievetsky** [comment]
@evasomething is working on it here: https://github.com/implydata/plywood/pull/20

**Comment by vogievetsky** [comment]
Woops, forgot to close it after that PR was merged.
