### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by krismolendyke** [implydata/pivot#99]
When`sourceListScan` is set to `disabled` the error message:

`Error: sourceListScan must be disabled or auto is ('disabled')` 

is confusing since it _is_ set to `disabled`.  The message should be changed to remove the trailing `d` and suggest that it must be `disable or auto`.  Small thing but it took me a few minutes to dig up.  Thanks!

https://github.com/implydata/pivot/blob/6dff93a13da641df59a7cbb13a2ede45a2052137/src/server/utils/data-source-manager/data-source-manager.ts#L42-L43

**Comment by vogievetsky** [comment]
On no, my dyslexia is acting up. Thank you so much for the issue.
